### ISSUE TITLE
Permanently change addresses

### ISSUE THREAD

**Issue by hpaantee** [roesel/elliptec#8]
Hi, 

great project! I just wanted to point out that the readme gives the impression that you would need to change the addresses every time you lose power. If you use the "Save user data" button under the Settings tab, the address change is saved permanently. 
There is also a corresponding command SAVE_USER_DATA

**Comment by roesel** [comment]
Hi, thanks for the feedback, I appreciate it. While you are right that the user data can be saved, this library is not able to do this at the moment, since the command you suggest has not been implemented. Therefore, unless you go and change the addresses permanently using the ELLO software, you really do have to set the addresses again after power loss most of the time. Or am I misunderstanding you?

**Comment by roesel** [comment]
I have went ahead and attempted to implement this feature in commit https://github.com/roesel/elliptec/commit/3b79ad606c46b2b7430b106dae15642ba65e9cef.
Since I do not have access to elliptec devices anymore, would you be able to test whether it works? 
Thank you!

**Comment by hpaantee** [comment]
Sorry for the late response. I just checked your new version. 
The` save_user_data()` function works like a charm, even after a reboot.

**Comment by roesel** [comment]
I am very happy to hear that. Thanks for getting back to me! ❤
